services:
  local-pypi:
    build:
      context: pypi
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./pypi/packages:/data/packages
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8888/health/"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - local_network

  local-pypi-tester:
    image: python:3.12-slim
    command: ["/bin/bash", "/tmp/scripts/run.sh"]
    depends_on:
      local-pypi:
        condition: service_healthy
    volumes:
      - ./pypi/packages:/tmp/packages
      - ./pypi-tester:/tmp/scripts
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
