services:
  local-pypi:
    build:
      context: pypi
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./pypi/packages:/data/packages
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8888/health/"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - local_network

  tester:
    image: python:3.12-slim
    command: >
      sh -c "
      pip install --upgrade pip &&
      pip install --trusted-host local-pypi --index-url http://local-pypi:8888/simple samplelib --no-deps
      "
    depends_on:
      local-pypi:
        condition: service_healthy
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
